# fly.toml app configuration file generated for resumerater-final-falling-star-2923 on 2024-12-01T15:01:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resumerater-final-falling-star-2923'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 2
